language: minimal

if: tag IS present

before_deploy: tar --exclude="./.*" -zcf ${TRAVIS_BUILD_DIR}/../bcrm_${TRAVIS_TAG}.tar.gz -C ${TRAVIS_BUILD_DIR} .

deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file_glob: true
  file:
    - ../bcrm_${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    repo: Jeansen/bcrm
    tag: true
    branch: $TRAVIS_TAG
